### ISSUE TITLE
Include developit/mitt in the benchmark

### ISSUE THREAD

**Issue by g3r4n** [Morglod/tseep#16]
Can you include mitt into the benchmark ? it's really light just want to know how is it compare to yours and see which one to choose between fast and 

[developit/mitt](https://github.com/developit/mitt)

**Comment by Morglod** [comment]
Thanks for reference; Added to benchmarks!
https://github.com/Morglod/tseep/blob/master/benchmarks/results.md

**Comment by 3rd** [comment]
@Morglod could the benchmarks be wrong because of Benchmark.js?
Made some measurements and started a related discussion here: https://github.com/tinylibs/tinybench/issues/42#issuecomment-1594588579
Would be greatly appreciated if you could pitch in, thanks!

**Comment by Morglod** [comment]
Actually when you emit events with tseep, you call listeners directly.
I mean its almost as fast as do this:

```
function emitEvent() {
   listener1();
   listener2();
}

emitEvent();
```

So it is as fast as reading value from object by string key and calling empty function.
(1400m ops on read vs 1300m ops on emit on your results).

While every other event emitter iterate over array of listeners which is a looot slower.  
And of course a bit more magic optimizations 😄 

---

Full answer:
https://github.com/tinylibs/tinybench/issues/42#issuecomment-1595625881
