### ISSUE TITLE
Does not support ...rest parameter

### ISSUE THREAD

**Issue by Madd0g** [Morglod/tseep#25]
Not sure if this is a known issue, I tried replacing event emitters in my codebase and my tests failed because I was getting extra things in arrays. Apparently I had an events mapper somewhere that did this:

```js
events.forEach((event) => {
     this.on(event, (...args: any[]) => handler(event, ...args));
});
```

and my tests kept showing me like 6-7 undefined values at the end of my values. I think it's due to the ...rest parameter?

**Comment by Morglod** [comment]
Its probably this code:
```ts
function emit(this: EventEmitter, event: string, a: any, b: any, c: any, d: any, e: any) {
   // ...
        if (listener.argsNum < 6) {
            listener(a, b, c, d, e);
   // ...
```

Reason for this is that its fastest approach to have fixed length of arguments.

Can you please provide example why you need to test number of arguments?

Also if its more than 5, than it could be something else, in that case please provide event emitting code and specify what emitter you are using (default or safe)

**Comment by Madd0g** [comment]
> Can you please provide example why you need to test number of arguments?

In the code, I'm iterating over a list of events like the above and connecting listeners. Every one of these events could have different number of arguments.

In the test, I'm spying on an event handler (that is hooked up with these `...args`) and then checking if it has been called with a certain set of arguments, but I'm getting more arguments than expected.

The funny thing, in the test itself, I was using `...args` too (it's an event that kinda bounces around) so I was seeing this "effect" twice.

**Comment by Morglod** [comment]
I understood. I mean I agree that different number of arguments is not 100% right thing, but I never saw code that relies on this. undefined value for not presented argument is right. Passing array's element through arguments is very bad, so I think you should test values, not length of arguments.

Something like:

```
testingArgs: [ 1,2,3,4,5 ... ]
emit event (...testingArgs)
listener(...args) {
   for each testingArgs {
        args[i] == testingArgs[i]
   }
}
```

**Comment by Madd0g** [comment]
> but I never saw code that relies on this

I feel like when dealing with events in a systemic fashion (for example, I have 2 places where events from one thing are broadcasted/mapped to another thing). So it becomes `(eventName, ...eventArgs)`.

It's not a big deal, it's just that I can't use a spy and `toHaveBeenCalledWith()` directly, it's easy to solve, just a little messy.

**Comment by Morglod** [comment]
Will add it to known issues

Agree it's a bit messy, but its a tradeoff for performance

Actually better evade spread operator as much as possible if you aim to performance

Thank you for highlighting this thing!
